version: "3.8"

services:
  central_library:
    image: rbojan2000/central-library
    container_name: central-library
    build:
      context: ./central-library
      dockerfile: Dockerfile
    depends_on:
      - central_library_db
    networks:
      - network
    ports:
      - 9080:9080

  central_library_db:
    image: mongo
    container_name: central_library_db
    restart: on-failure
    networks:
      - network

  nis_library:
    image: rbojan2000/city-library
    container_name: nis_library
    build:
      context: ./city-library
      dockerfile: Dockerfile
    depends_on:
      - nis_library_db
    networks:
      - network
    ports:
      - 9081:9081
    environment:
      - LIBRARY_DB_HOST=nis_library_db
      - LIBRARY_DB_PORT=27017
      - LIBRARY_PORT=9081
      - CITY=NIS

  novi_sad_library:
    image: rbojan2000/city-library
    container_name: novi_sad_library
    build:
      context: ./city-library
      dockerfile: Dockerfile
    depends_on:
      - novi_sad_library_db
    networks:
      - network
    ports:
      - 9082:9082
    environment:
      - LIBRARY_DB_HOST=novi_sad_library_db
      - LIBRARY_DB_PORT=27017
      - LIBRARY_PORT=9082
      - CITY=NOVI-SAD

  belgrade_library:
    image: rbojan2000/city-library
    container_name: belgrade_library
    build:
      context: ./city-library
      dockerfile: Dockerfile
    depends_on:
      - belgrade_library_db
    networks:
      - network
    ports:
      - 9083:9083
    environment:
      - LIBRARY_DB_HOST=belgrade_library_db
      - LIBRARY_DB_PORT=27017
      - LIBRARY_PORT=9083
      - CITY=BELGRADE

  nis_library_db:
    image: mongo
    container_name: nis_library_db
    restart: on-failure
    networks:
      - network

  novi_sad_library_db:
    image: mongo
    container_name: novi_sad_library_db
    restart: on-failure
    networks:
      - network

  belgrade_library_db:
    image: mongo
    container_name: belgrade_library_db
    restart: on-failure
    networks:
      - network

networks:
  network:
    driver: bridge
 
