name: Docker Build and Push

on:
  push:
    branches: [main]
    paths:
      - 'central-library/**'
      - 'belgrade/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            central-library:
              - 'central-library/**'
              - 'belgrade/**'
      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker images
        if: steps.changes.outputs.central-library == 'true'
        run: |
          docker build -t rbojan2000/central-library ./central-library
          docker push rbojan2000/central-library:latest

      - name: Build and push Docker images
        if: steps.changes.outputs.belgrade == 'true'
        run: |
          echo 'hello from belgrade'
